# -*- coding: utf-8 -*-
"""06_05_24 Deep Learning e IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1-ZKUI8Uq8OB74XEkGtFrjUNt0iMmh5

## Classificação de Espécies Iris com Redes Neurais Multicamadas

#Breno Azevedo
"""

from sklearn.neural_network import MLPClassifier
from sklearn import datasets
import pandas as pd

iris = datasets.load_iris()

entradas = iris.data #Pega as entradas
saidas = iris.target #Pega a saída

#Montando a arquitetura da rede
#objeto                    orientação objeto
redeneural = MLPClassifier(verbose=True, #Para printar a "epóca"(deixa lerdo) false=datasets reais
                           max_iter=10000, #máximo de interações
                           tol=0.000001,#tolerância
                           activation='relu', #Função de ativação
                           #hidden_layer_sizes=(30,30,30, #camadas ocultas
                           learning_rate_init=0.0001 #taxa de aprendizado
                           )

iris.data

redeneural.fit(entradas,saidas)

redeneural.predict([[6.7,3.0,5.,2.3]])