# -*- coding: utf-8 -*-
"""revisão de python 19/02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CKuGf3yefobDIaHopv8tEIC7_ukl2_9V
"""

lista = [20, 5.5, "a", True]
lista

lista[0] = 21
lista

lista.append(500)
lista

lista.insert(3, 80)
lista



lista.insert(4, "tomale")
lista

lista.pop (5)

lista

lista2 = [1, 2, 3]

lista

lista2

lista.append (lista2)

lista2

lista

lista[-1][1]



lista.pop (-1)
lista

lista = lista + lista2

lista = lista + lista2
lista

x = lista[:3]
#indice começa do zero (lista 21, 5.5, 'a', 80, 'tomale', True, 500, 1, 2, 3 / 21 = 0 | 3 = 9)
x

x = lista[4:-1]
x

tupla = (1, 2, 3)
print(type(lista))
print(type(tupla))

tupla = (2,)
type(tupla)

tupla = (2)

type(tupla)

#tupla não altera, já a lista você pode alterar com pop, append e insert)

#dicionario

dragonball = {
    'Goku': 'Protagosnista',
    'Vegeta': "Antagonista",
    'Freeza': 'Vilão',
    'Kuririn': 'inútil'
}

#Chave(keys) : Valor(values)

dragonball

dragonball['Goku']

dragonball['Goku'] = 'apelão'

dragonball

del dragonball['Kuririn']
dragonball

dragonball.keys()

dragonball.values()

dragonball.items()

x = (1,4)
x

x, y = (1, 4)
print(x)
print(y)

for coisa in dragonball.items():
  print(coisa)

for personagem, papel in dragonball.items():
  print(personagem, "é", papel)
  #for = pra cada | in = dentro)

'pikachu' in dragonball

total = 0

for valor in range(0, 11):
  total = total + valor

total

salarios = [3000, 15000, 50000]
total= 0
for s in salarios:
  total += s #total = total +s

  print(salarios)

def f(x):
  return x**2

  f(5)

def calcula_salario_liq(sal_bruto, bonus, comissao, imposto):
  total = sal_bruto + bonus + comissao - imposto
  return total

calcula_salario_liq(15000, 2000, 1000, 5000)

def calc_sal(sal, bonus=0):
  total = sal+bonus
    if total > 7000:
#if = se
      return total*(1-0.275)
    elif total >= 4000 and total <= 7000:
      return total*(1-0.275)
    else:
      return total

      calc_sal

